Add files via upload
Este é um simples jogo de par ou ímpar porém há um erro que eu não compreendo/consigo resolver:
File "C:/Users/Markos/PycharmProjects/AulasPython/Exercícios/Desafio068.py", line 18, in <module>
    if player in 'IiÍí':
TypeError: 'in <string>' requires string as left operand, not int